### ISSUE TITLE
Arrgh, audio aliginment

### ISSUE THREAD

**Issue by javaarchive** [arduano/Zenith-MIDI#1]
I use KMC(Keppy's Midi Converter) to renderer audio. It usually removes any beginning empty notes. The problem I get with rendering with audio is that the audio starts before the first note hits the piano roll.
Is it possible to configure Zenith to start adding the audio in when the first note is rendered on the piano roll

**Comment by arduano** [comment]
Ok so, zenith aligns the audio using FFMPEG's audio offset command. This doesn't add empty audio at the beginning, but rather it writes information into the file saying how much offset there should be. Most video players recognise that and offset the audio correctly. However, programs like After Effects and Premier Pro don't recognise it and therefore don't have the audio aligned correctly. I recommend just aligning it manually, when using a video editor.

Also, if you are uploading the video straight to youtube, then youtube actually does in fact recognise the audio offset correctly. I have uploaded videos before like this.

**Comment by javaarchive** [comment]
At least chrome is smart enough to play it correctly

**Comment by Thewolfatatelogokid** [comment]
How do you turn on that offset command? i got the same problem too

**Comment by arduano** [comment]
It might be the software you're using not recognizing the offset flag. I used ffmpeg's audio offset feature which just offsets the audio track start, rather than inserting empty audio at the beginning (which would require re-encoding the audio track and generally it was pretty difficult to implement).

It's designed to be a simple hack for quick renders, for anything proper you can just manually align the audio track in editing software.
