### ISSUE TITLE
No audio while playing MIDI files

### ISSUE THREAD

**Issue by NewAgeDerpDerp** [arduano/Zenith-MIDI#31]
Pretty self explanatory. While attempting to play ONESTOP.MID there is no response in my headset and the Windows Sound Mixer shows that there isn't any instance of "zenith" open at all.

**Comment by ApexdaGamer** [comment]
Make sure you have KDMAPI on, with OmniMidi installed for the KDMAPI drivers. Then, it should play midis on preview.

**Comment by arduano** [comment]
Fuck sorry I completely missed this issue

Yeah as the comment above says, make sure OmniMidi is installed on latest version

on the load midi tab, there should be a  "Disable KDMAPI" button enabled. if it's there and clickable, that means omnimidi is detected.

Make sure you have soundfonts in omnimidi as well

**Comment by NewAgeDerpDerp** [comment]
Neither solution worked, still completely silent.
I’m trying to play onestop.mid if that helps

**Comment by arduano** [comment]
Hmm, it might be easier to solve this over discord. Maybe join the zenith server and ping me in the bug discussions channel?

**Comment by NewAgeDerpDerp** [comment]
I don't have a link to the Discord or the User ID

**Comment by arduano** [comment]
https://discord.gg/rKYvqVB
and I'm Arduano over on discord

**Comment by SJRNoodles** [comment]
same happening with me too

**Comment by arduano** [comment]
Ok so, OP's problem was that omnimidi had no sound fonts in it

Please follow this checklist:
- Omnimidi is installed (https://github.com/KeppySoftware/OmniMIDI/releases)
- Restarted computer
- Added soundfonts to omnimidi's configuration panel
- Restarted zenith
- The midi is a piano-only midi if the soundfont is piano-only, otherwise make sure that the soundfont supports all instruments
