### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by O2C14** [arduano/Zenith-MIDI#44]

**Comment by O2C14** [comment]
This software can't play audio

**Comment by Kaydax** [comment]
Zenith doesn't play audio unless in preview mode with OmniMIDI installed. When rendering a video, zenith outputs no audio and only gives you a video with no audio. To get audio for the video, you have to render the audio using either Keppy's MIDI Converter or OmniConverter.

**Comment by arduano** [comment]
Please follow this checklist:

- Omnimidi is installed (https://github.com/KeppySoftware/OmniMIDI/releases)
- Restarted computer
- Added soundfonts to omnimidi's configuration panel
- Restarted zenith
- The midi is a piano-only midi if the soundfont is piano-only, otherwise make sure that the soundfont supports all instruments
